#!/bin/bash
# Sam Shepard - 2020-08
# For renewing and maintaining a Kerberos Ticket-Granting-Ticket on a remote FreeIPA / CDP host.
# Some code inspired by: https://cat.pdx.edu/platforms/linux/user-environment/kerberos/renew

hUser=$(whoami)
hAdmin=vfn4@cdc.gov
if [ "$#" -eq "1" ];then
	hHost=$1
else
	echo -e "Usage:\n\t$0 <host>"
	exit 0
fi
host $hHost >/dev/null 2>&1 || { echo "Cannot find host '${hHost}'"; exit 1; }

hLogin=$hUser@$hHost
CMD='klist -s || kinit; pgrep -U $USER krenew >/dev/null || ( kinit -R && krenew -H 60 -K 60 -L -b )'

exec 3>&1
OUTPUT=$(ssh -t $hLogin "$CMD" 2>&1 1>&3)
STATUS=$?
exec 3>&-

if [ "$STATUS" -ne "0" ];then
	echo "ERROR ($STATUS): $0" 1>&2
	echo "TRIED CMD: ssh $hLogin '$CMD'" 1>&2
        [ "$STATUS" -eq "127" ] && echo "NOTE: kstart may not be installed on $hHost, please contact $hAdmin."
	echo "-----------START-LOG---------------" 1>&2
	echo "$OUTPUT"|tail -n +45 1>&2
	echo "-----------END-LOG-----------------" 1>&2	
	exit $STATUS
fi
