#!/bin/bash

hUser=$(whoami)

if [ "$HADOOP_HOST" != "" ];then
	hHost=$HADOOP_HOST
else
	hHost=cdp-client-01.biotech.cdc.gov
fi
hLogin=$hUser@$hHost

# Handle remote vs local execution
SSH="ssh $hLogin"
EXEC=$SSH
JUMP=31
if [ "$(hostname -s|cut -f1 -d'-')" == "cdp" ];then
	EXEC="eval"
	SSH=""
	JUMP=1
fi

if [ "$#" -eq "1" ];then
	lFile=$1
	hDir=/user/$hUser
	hFile=$hDir/$(basename $lFile)
elif [ "$#" -eq "2" ];then
	lFile=$1
	if [ "${2: -1}" == "/" ];then
		hDir="$2"
		hFile="${hDir}$(basename $lFile)"
	else 
		hDir=$(dirname $2)
		hFile=$2
	fi
else
	echo -e "Usage:\n\t$0 <localfile> [/hdfs/path/dir/|/hdfs/path/file]"
	exit 0
fi

if [ ! -p "$lFile" ] && [ ! -r "$lFile" -o ! -s "$lFile" ];then
	echo -e "Invalid file: $lFile"
	exit 1
fi	

OUTPUT=$(cat $lFile | $EXEC "hdfs dfs -appendToFile - $hFile" 2>&1)
STATUS=$?
if [ "$STATUS" -ne "0" ];then
	echo "ERROR ($STATUS): $0" 1>&2
	echo "TRIED CMD: cat $lFile | $SSH \"hdfs dfs -put -f - $hFile\"" 1>&2
	echo "-----------START-LOG---------------" 1>&2
	echo "$OUTPUT"|tail -n +${JUMP} 1>&2
	echo "-----------END-LOG-----------------" 1>&2
	exit $STATUS
fi
