#!/bin/bash
# Sam Shepard - hjar - 2017-05-05

if [ "$HADOOP_HOST" != "" ];then
	hHost=$HADOOP_HOST
else
	hHost="flu-hadoop-04.biotech.cdc.gov"
fi

hUser=$(whoami)
hLogin=$hUser@$hHost

if [ "$#" -eq "1" ];then
	jar=$1
elif [ "$#" -eq "2" ];then
	jar=$1
	argString=$2
else
	echo -e "Usage:\n\t$0 <jarpath> [argument_string]"
	exit 0
fi

ssh $hLogin stat $jar >/dev/null 2>&1
if [ "$?" -eq "0" ];then
	ssh $hLogin "hadoop jar $jar $argString" >/dev/null 2>&1
else
	exit 2 
fi
